require:
  - "rubocop-rails"
  - "rubocop-rspec"
  - "rubocop-rspec_rails"
  - "rubocop-factory_bot"

AllCops:
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "node_modules/**/*"
    - "vendor/**/*"
    - "bin/*"
    - "db/migrate/*"
Layout/LineLength:
  Exclude:
    - "config/**/*"
    - "lib/**/*"
    - "spec/**/*"
Lint/ShadowingOuterLocalVariable:
  Exclude:
    - "lib/**/*"
Metrics/BlockLength:
  Exclude:
    - "app/admin/**/*"
    - "config/**/*"
    - "lib/**/*"
    - "spec/**/*"
Metrics/CyclomaticComplexity:
  Exclude:
    - "lib/**/*"
    - "spec/**/*"
Metrics/PerceivedComplexity:
  Exclude:
    - "lib/**/*"
    - "spec/**/*"
Naming/PredicateName:
  Exclude:
    - "lib/**/*"
Naming/VariableName:
  Exclude:
    - "spec/**/*"
Security/Open:
  Exclude:
    - "lib/**/*"
Style/ClassAndModuleChildren:
  Exclude:
    - "spec/**/*"
    - "app/controllers/**/*"
Style/Documentation:
  Enabled: false
Style/DocumentationMethod:
  Enabled: false
Style/IdenticalConditionalBranches:
  Exclude:
    - "app/**/*"
Rails/SkipsModelValidations:
  Exclude:
    - "**/*"
Metrics/AbcSize:
  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "lib/**/*"
    - "spec/**/*"
Metrics/MethodLength:
  Max: 15
  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "lib/**/*"
    - "spec/**/*"
Lint/DuplicateBranch:
  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "lib/**/*"
Rails/UniqueValidationWithoutIndex:
  Exclude:
    - "app/**/*"
Rails/I18nLocaleTexts:
  Exclude:
    - "app/**/*"
Rails/HasAndBelongsToMany:
  Exclude:
    - "app/**/*"

RSpec/PendingWithoutReason:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false

# To integrage with rswag
# https://github.com/rswag/rswag/issues/138
RSpec/DescribeClass:
  Enabled: false
RSpec/EmptyExampleGroup:
  Enabled: false
RSpec/RepeatedDescription:
  Enabled: false
RSpec/RepeatedExample:
  Enabled: false
RSpec/ScatteredSetup:
  Enabled: false
