version: "3.8"
services:
  postgresql:
    image: postgres:15
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    networks:
      - se_backend

  api:
    build:
      context: .
    environment:
      - RAILS_ENV=development
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOSTNAME=postgresql
      - POSTGRES_PORT=5432
    volumes:
      - ./:/rails
    ports:
      - 3000:3000
    networks:
      - se_backend
    depends_on:
      - postgresql

networks:
  se_backend:
    driver: bridge