default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['POSTGRES_HOSTNAME'] %>
  port: <%= ENV['POSTGRES_PORT'] %>
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: se_backend_development

test:
  <<: *default
  database: se_backend_test

production:
  <<: *default
  database: se_backend_production
  username: se_backend
  password: <%= ENV['SE_BACKEND_DATABASE_PASSWORD'] %>